- name: Playbook d'exploration de commandes
  hosts: 127.0.0.1
  tasks:
      - name: Whoami 
        local_action: command whoami
        register: command_identity
        
      - name: list du dossier home
        local_action: command ls ~
        register: command_home_folder
      
      - name: list du dossier de la clé
        local_action:  command ls /var/lib/awx 
        register: command_key_folder
        
      - name: obtention du working directory
        local_action: command echo "$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
        register: command_working_directory

      - name: affichage de l'utilisateur
        debug:
                var: command_identity.stdout

      - name: affichage du dossier home
        debug:
                var: command_home_folder.stdout_lines

      - name: affichage du dossier de la clé
        debug:
                var: command_key_folder.stdout_lines

      - name: affichage du dossier courant
        debug:
                var: command_working_directory.stdout_lines
